version: "3.8.1"

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - "data-base:/var/lib/mysql"
    ports:
      - 3306:3306

volumes:
  data-base:
